version: '3'

services:

    fuseki:
        build: ./fuseki
        container_name: sirapi_fuseki
        ports:
            - "3030:3030"
        networks:
            sirapi:
                aliases:
                    - fuseki
        volumes:
            -   sirapi-fuseki-data:/fuseki/databases
        restart: always

    fuseki-yasgui:
        build: fuseki-yasgui
        container_name: sirapi_fuseki_yasgui
        ports:
            - "8888:8888"
        networks:
            sirapi:
                aliases:
                    - fuseki-yasgui
        environment:
            # This should be a url that points to this container
            # Proxies to the /store/sparql endpoint for fuseki
            DEFAULT_SPARQL_ENDPOINT: "http://localhost:8888/sparql"
        depends_on:
            -   fuseki

    # The primary sirapi web app
    sirapi:
        build: ./
        restart: always
        container_name: sirapi
        tty: true
        ports:
            - "9000:9000"
        networks:
            sirapi:
                aliases:
                    - sirapi
        environment:
            # Uncomment below setting when using Solr Authentication. Then rename security.json.template under solr/solr-home/ folder to security.json. Add user & passowrd detail in the sirapi.conf/sirapi-docker.conf file. All changes are mandatory for Solr Authentication to work.
            # JAVA_OPTS: -Xms128m -Xmx12g -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=solr:SolrRocks
            # Comment out below setting when using Solr Authentication
            JAVA_OPTS: -Xms128m -Xmx12g
        volumes:
            # Creates a volume to store the various csv files. This allows the data
            #   to be persisted when the container is removed or when Hadatac is rebuilt.
            # Example command: docker cp <filename> sirapi:/root/app/csvs/unprocessed_csv

            # Comment out this option to use external binding
            # - sirapi-csvs:/sirapi/csvs
            # - sirapi-working_csv:/sirapi/working_csv
            #            - /Users/kandws01/Documents/merge3/local:/root/app/csvs  # Uncomment this option to use external binding
            # Creates a volume for the config files. This way configuration file changes
            #   are persisted when the container is removed or rebuilt.

            # Comment out this option to use external binding
            # - sirapi-conf:/sirapi/conf
            #            - /path in host server/conf:/root/app/conf # Uncomment this option to use external binding
            - /var/log/sirapi:/sirapi/logs
        links:
            - fuseki
        depends_on:
            - fuseki
            
    postgres:
      image: postgres
      expose:
        - "5432"
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: "PostgresPNS10!"

    drupal:
      image: drupal:9.5.2-php8.1-apache
      restart: always
      ports:
        - 8999:80
      links:
        - postgres
        - sirapi      
      depends_on:
        - postgres
        - sirapi      
      stdin_open: true
      tty: true            

volumes:
    sirapi-fuseki-data:
    # sirapi-conf:

networks:
    sirapi: